init commit
CHABNDHEANEE/explore-with-me pull request #1
Opened 2023-07-25 07:29 UTC by CHABNDHEANEE

2023-07-25 07:44 UTC, CHABNDHEANEE commented
Оказалось проще переписть весь сервер статистики, чем внедрять в него мейн. Вариант архитектуры из вебинара оказался удачней

2023-07-25 20:43 UTC, Fleaman777 requested changes

2023-07-25 20:43 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +public class CategoryServiceImpl implements ru.practicum.category.service.CategoryService {
думаю, можно не использовать полное название интерфейса, а оставить только CategoryService, 
это чуть упростит восприятие

2023-07-25 20:43 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +    public CategoryDto createCategory(NewCategoryDto newCategoryDto) {
метод изменяет состояние БД, правильней было бы его выполнять в транзакции, 

относится ко всем аналогичным местам

2023-07-25 20:43 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +        }
у Optional класса есть хороший метод orElseThrow 
отлично сюда впишется и сократит количество кода

2023-07-25 20:43 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +            states.addAll(Stream.of(State.values())
а нужно ли создавать эррейЛист, и потом в него добавлять все значения из State, 
почему бы сразу не сделать 
states = Stream.of(State.values())....

2023-07-25 20:43 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +    }
когда в методе много вложенных if-else ухудшается восприятие, 
попробуй немного упростить этот метод, 
например некоторые условия инвертировать, а что-то вынести в отдельные вспомогательные методы

аналагично в других похожих местах

2023-07-25 20:43 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +        statsClient.postHit("ewm-main-service", request.getRequestURI(), request.getRemoteAddr(), LocalDateTime.now());
"ewm-main-service" - можно было бы вынести в константу, что бы было удобно управлять этим значением, если оно будет меняться

2023-07-25 20:43 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +            if (request.getDescription().length() <= 7000 && request.getDescription().length() >= 20) {
так же, подобные значения 7000, 2000 и др. лучше выносить в константы с подходящим именем, и можно еще добавить комментарий, почему значение именно такое,
что бы в будущем не гадать, почему эта цифра именно такая

2023-07-27 07:30 UTC, Fleaman777 approved these changes

2023-07-27 07:30 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +        rangeStart = rangeStart == null ? LocalDateTime.now().minusYears(5) : rangeStart;
LocalDateTime.now() можно было бы вынести в локальную переменную, что бы не дублировать получение текущей даты

2023-07-27 07:30 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +    }
отлично, то, что нужно

2023-07-27 07:30 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/event/model/Event.java
> +@Data
Если будет время, рекомендую почитать:
https://habr.com/ru/companies/haulmont/articles/564682/
Это о том, почему @Data и JPA лучше вместе не использовать

2023-07-27 07:30 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +        rangeStart = rangeStart == null ? LocalDateTime.now() : rangeStart;
LocalDateTime.now() можно было бы вынести в локальную переменную, что бы не дублировать получение текущей даты

2023-07-29 18:31 UTC, merged